[package]
name = "irony"
version = "0.1.0"
authors = ["phil"]

[dependencies]
iron = "0.1.20"
router = "0.0.10"
mount = "0.0.7"

[dependencies.staticfile]
git = "https://github.com/iron/staticfile.git"
